# Adresse du frigo (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_produit?useSSL=false&allowPublicKeyRetrieval=true
# Nom d'utilisateur (par défaut dans XAMPP)
spring.datasource.username=root
# Mot de passe (par défaut dans XAMPP, c'est vide)
spring.datasource.password=
# Pilote pour MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Laisse Spring créer les tables automatiquement (la magie !)
spring.jpa.hibernate.ddl-auto=update
# Affiche les requêtes SQL dans la console (pour apprendre)
spring.jpa.show-sql=true
# Dis à Spring qu'on parle le langage MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect